apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
    - name: phpmyadmin
      protocol: TCP
      port: 5000
      targetPort: 80
  selector:
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      restartPolicy: Always
      containers:
      - image: phpmyadmin
        name: phpmyadmin
        imagePullPolicy: Never
        ports:
          - containerPort: 80
            name: phpmyadmin
          